let Server,getServerById,getUser;_5e3‍.x([["setupSocketIO",()=>setupSocketIO],["default",()=>_5e3‍.o]]);_5e3‍.w("socket.io",[["Server",["Server"],function(v){Server=v}]]);_5e3‍.w("../controller/server",[["getServerById",["getServerById"],function(v){getServerById=v}]]);_5e3‍.w("../controller/user",[["getUser",["getUser"],function(v){getUser=v}]]);



       function setupSocketIO(server) {
  const io = new Server(server, {
    cors: {
      origin: "http://localhost:3001",
    },
  });

  io.on("connection", async (socket) => {
    const username = socket.handshake.query.name;
    const user = await getUser(username);
    _5e3‍.g.console.log("A user connected:", username);
    
    let channel, group, server;
    // Handle joining a channel
    socket.on("joinServerChannel", async (data) => {
      try {
        /* console.log("CHANNEL DATA", data) */
         server = await getServerById(data.serverId);
        if(data.groupId)
        {
          group = server.groups.find((el) => el._id.toString() === data.groupId)
          channel = group.channels.find((el) => el._id.toString() === data.channelId);
        }
        else
        {
         channel = server.channels.find((el) => el._id.toString() === data.channelId);
        }
        /* console.log("joinServerChannel", data, "server", server, "channel", channel); */
        socket.join(channel._id.toString());
        socket.emit("getAllMessages", channel.messages)
      } catch (error) {
        _5e3‍.g.console.error(error);
        socket.emit("error", "An error occurred while joining the channel");
      }
    });
     
      socket.on("serverMessage", async (data) =>{
          try {
            _5e3‍.g.console.log("ServerMessage", data)
            const { message, hash } = data;
            const messageObj = { userId: user._id , text: message, hash}
            channel.messages.push(messageObj);
            await server.save();
            io.to(channel._id.toString()).emit("receiveMessage", messageObj);
          } catch (error) {
            _5e3‍.g.console.error(error);
            socket.emit("error", "An error occurred while joining the private chat");
          }
        })

     let chat, withUser;
    socket.on("joinPrivateChat", async (data) => {
      try {
        chat = user.privateChats.find((el) => el._id.toString() === data._id);
        _5e3‍.g.console.log("joinPrivateChat", data, "chat", chat, "user", user);
        socket.join(chat._id.toString());
        socket.emit("getAllMessages", chat.messages)
      } catch (error) {
        _5e3‍.g.console.error(error);
        socket.emit("error", "An error occurred while joining the private chat");
      }
    });
   
    socket.on("privateMessage", async (data) => {
      try {
        const { message, hash } = data;
        const messageObj = { userId: user._id , text: message, hash}
        chat.messages.push(messageObj)
        await user.save()
        io.to(chat._id.toString()).emit("receiveMessage", messageObj);
        _5e3‍.g.console.log("privateMessage", data);
      } catch (error) {
        _5e3‍.g.console.error(error);
        socket.emit("error", "An error occurred while joining the private chat");
      }
    });



    // Handle leaving a channel
    socket.on("leaveChannel", ({ channelId }) => {
      socket.leave(channelId);
    });


    socket.on("disconnect", () => {
      _5e3‍.g.console.log("A user disconnected:", username);
    });
  });
}

_5e3‍.d(setupSocketIO);
